var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var c=0;return $jscomp.iteratorPrototype(function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,c){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var d=0,e={next:function(){if(d<b.length){var f=d++;return{value:c(f,b[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(b,c,d,e){if(c){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in d||(d[f]={});d=d[f]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.values",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b,d){return d})}},"es8","es3");
$jscomp.findInternal=function(b,c,d){b instanceof String&&(b=String(b));for(var e=b.length,f=0;f<e;f++){var k=b[f];if(c.call(d,k,f,b))return{i:f,v:k}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6","es3");
(function(b,c){function d(g){if(g.origin===b.origin||g.origin===this.mainWindow.origin)try{var a=g.data.split(":");if("ping"==a[0])c("iframe.interactive")[0].contentWindow.postMessage("authorAPIPing:"+a[1],b.origin);else{var h=authorAPI[a[0]](a[1],a[2]);"get"==a[0]&&c("iframe.interactive")[0].contentWindow.postMessage("authorAPIGet:"+a[1]+":"+h,b.origin)}}catch(t){}}var e={bind:function(b,a){this._callbacks=this._callbacks||{};b.split(" ").forEach(function(b){this._callbacks[b]=this._callbacks[b]||
[];this._callbacks[b].push(a)},this);return this},trigger:function(){var b=Array.prototype.slice.call(arguments);var a=b.shift();(a=this._callbacks&&this._callbacks[a])&&a.forEach(function(a){a.apply(this,b)},this)},unbind:function(b,a){if(0===arguments.length)return this._callbacks={},this;if(!b)return this;for(var h in b.split(" ")){var c=this._callbacks&&this._callbacks[h];c&&(a?c.forEach(function(b,c){if(b===a){var g=g.slice();g.splice(c,1);this._callbacks[h]=g}},this):delete this._callbacks[h])}return this}},
f=function(){var b=function(a){this.url=a;this.dfd=null};b.prototype={check:function(){if(this.dfd)return this.dfd.promise();this.dfd=c.Deferred();c.get(this.url).then(function(){this.dfd.resolve(!0);this.dfd=null}.bind(this)).fail(function(a){this.dfd.resolve(!(401===a.status||403===a.status));this.dfd=null}.bind(this));return this.dfd.promise()}};return b}(),k=function(){var b=function(a,b,c){this.next=this.current=null;this.authToken=a;this.apiUrl=b;this.observer=c};b.prototype={enqueue:function(a){this.next=
this._buildAjaxFunctionFromData(a);this.current||this._processNext()},hasPending:function(){return!!this.current},_buildAjaxFunctionFromData:function(a){return c.proxy(function(){c.ajax(this.apiUrl,{type:"PUT",data:{authenticity_token:this.authToken,data:JSON.stringify(a),_method:"PUT"}}).done(c.proxy(this._processNext,this)).done(c.proxy(this._notifyObserver,this)).fail(c.proxy(this._onFail,this))},this)},_retry:function(){this.next?this._processNext():this.current()},_processNext:function(){this.current=
this.next;this.next=null;this.current&&this.current()},_notifyObserver:function(a){this.observer.update({type:"response",data:a})},_onFail:function(a){this.observer.update({type:"error",response:a.responseText});setTimeout(c.proxy(this._retry,this),2E3)}};return b}(),m=function(){var g=function(a){this.authToken=a.authToken;this.apiUrl=a.apiUrl;this.observer=new l(this,a.mainWindow);this.queues={}};g.prototype={process:function(a,b){(this.queues[a]||(this.queues[a]=new k(this.authToken,this.apiUrl,
this.observer))).enqueue(b);this.busy()},hasPending:function(){for(var a in this.queues)if(this.queues.hasOwnProperty(a)&&this.queues[a].hasPending())return!0;return!1},update:function(){this.hasPending()||this.idle()},busy:function(){c(b).off("beforeunload").on("beforeunload",function(){return"There are pending requests. If you close the window, you may lose data."})},idle:function(){c(b).off("beforeunload")}};return g}(),l=function(){var b=function(a,b){this.main=b;this.observer=a};b.prototype=
{update:function(a){this.main&&this.main.postMessage(a,"*");this.observer&&this.observer.update(a)}};return b}(),n=function(){var b=function(a){this.api=a;this.currentViewMode=null;a.ready().then(function(a){a.getBook().addEventListener("open_page",this.trigger.bind(this,"open_page"))}.bind(this))};_(b.prototype).extend(e,{setCurrentViewMode:function(a){this.currentViewMode=a},getCurrentViewMode:function(){return this.currentViewMode}});return b}(),p=function(){var d=function(a){a.ready().then(function(a){a.getBook().addEventListener("open_external_hotspot",
this.open.bind(this))}.bind(this))};_(d.prototype).extend({open:function(a){a=this.url(a);this.isMobile()?b.open(a):this.openInIframe(a)},close:function(){this.backdrop&&this.backdrop.remove();this.iframe&&this.iframe.remove();this.backdrop=this.iframe=null},isMobile:function(){return 988>=c(b).width()},openInIframe:function(a){this.backdrop=this.$backdrop().appendTo("body").click(this.close.bind(this));this.iframe=this.$iframe(a).css("visibility","hidden").appendTo("body").on("load",function(){c(this).css("visibility",
"visible")})},url:function(a){return"/interactives/"+a},$iframe:function(a){return c("<iframe></iframe>").attr({frameborder:0,scrolling:"no",allowfullscreen:!0}).attr("src",a).attr("style","position: fixed; z-index: 1050; top: 50%; left: 50%; width: 988px; margin-left: -494px; height: 679px; margin-top: -339.5px").addClass("interactive-dialog")},$backdrop:function(){return c("<div></div>").addClass("modal-backdrop").css(this.backdropStyle())},backdropStyle:function(){return{top:0,left:0,right:0,bottom:0,
zIndex:1040,opacity:.7,position:"fixed",backgroundColor:"#000"}}});return d}(),q=function(){var b=function(a){this.api=a};_(b.prototype).extend({set:function(a){this.data=a;this.api.initialized().then(function(a){a=a.getBook();a.register&&a.register("has-resources",this.hasResources.bind(this))}.bind(this))},hasResources:function(a){for(var b in this.data){var c=this.data[b];if(a.page>=c.start&&a.page<=c.end)return!0}return!1}});return b}(),r=function(){var d=function(a){this.values={};this.tainted=
!1;this.dfdEngineInitialized=c.Deferred();this.dfdEngineReady=c.Deferred();this.mainWindow=a;this.ajaxManager=new m({mainWindow:a});this.sessionStatus=new f("/api/profile.json");this.resourcePanelManager=new n(this);this.taggingManager=new q(this);this.hotspotManager=new p(this)};d.prototype={initializeValues:function(a){this.values=a},setEngine:function(a){var b=this;this.engine=a;a.addEventListener("lo:submit",function(){return b.onLOSubmit()});a.addEventListener("interaction:start",function(){return b.onInteractionStart()},
this,{once:!0});this.dfdEngineInitialized.resolve(a);a.ready().then(function(){this.dfdEngineReady.resolve(a)}.bind(this))},initialized:function(){return this.dfdEngineInitialized.promise()},ready:function(){return this.dfdEngineReady.promise()},setScreenIdGetterForDigitalBooks:function(){try{var a=JSON.parse(this.values.data).interaction&&"interaction"||"interaction_0";this.getScreenIdFor=function(){return a}}catch(h){}},setTagging:function(a){this.taggingManager.set(a)},isResourcesPanelEnabled:function(){return!!this.values.show_resources_panel},
resourcePanelMode:function(a){this.ready().then(function(b){b.getBook().resourcePanelMode(a)})},resourcesUrl:function(a){a=a||{};this.sessionStatus.check().then(function(a){a||(b.top.location.href="/users/login?user_return_to="+b.top.location.href)});return this._resourcesUrl||(this._resourcesUrl=function(){var c=a.page-a.offset+1,d,e,f,g=this.resourcePanelManager.getCurrentViewMode();(d=/courses\/(\d+)/.exec(b.location.href))&&(e=d[1]);(d=/(\d+).html/.exec(b.location.href))&&(f=d[1]);c="/app/courses/"+
e+"/digital_books/"+f+"/page/"+c;g&&(c=c+"/mode/"+g);return c}.call(this))},set:function(a,b){"object"==typeof console&&"function"==typeof console.log&&console.log("set key:"+a+" value:"+b);if(this.values[a]!=b){var c={};this.values[a]=c[a]=b;"undefined"!=typeof this.values.api_url&&(this.ajaxManager.authToken=this.values.authenticity_token,this.ajaxManager.apiUrl=this.values.api_url,this.ajaxManager.process(a,c))}},get:function(a){"object"==typeof console&&"function"==typeof console.log&&console.log("get key:"+
a+" value:"+this.values[a]);return this.values[a]},closeModal:function(a){var b=a.find(".interactive-dialog");b.length||(b=a.find("iframe.hotspot.modal-content").parent());b.fadeOut(function(){c(this).remove()})},closeHotspot:function(){this.hotspotManager.close()},finish:function(a){a=c(b.parent.document);if(this.ajaxManager.hasPending())return setTimeout(this.finish.bind(this),500),!1;if(top==b)b.close();else if(_.isUndefined(top.Osp))this.closeModal(a),a.find(".modal-backdrop").remove();else try{top.Osp.InteractivePlayer.player.hideModal(),
top.Osp.InteractivePlayer.player.removeModal()}catch(h){top.Backbone.Radio.channel("learning_object").request("finish")}this.mainWindow&&this.mainWindow.postMessage({type:"lo:finish"},b.origin)},notifyAnswers:function(){var a=this;try{this.engine.getLO().getUserAnswers().then(function(c){return a.mainWindow.postMessage({type:"lo:answers",data:c},b.origin)})}catch(h){}},onLOSubmit:function(){if(this.mainWindow){var a=this.values.score,c=this.values.api_url;this.notifyAnswers();this.mainWindow.postMessage({type:"lo:submit",
data:{score:a,useAPI:!!c}},b.origin)}},onInteractionStart:function(){this.mainWindow&&this.mainWindow.postMessage({type:"interaction:start"},b.origin)}};return d}();b.authorAPI=new r(top);"undefined"!=typeof b.attachEvent&&b.attachEvent("onmessage",d);"undefined"!=typeof b.addEventListener&&b.addEventListener("message",d,!1)})(window,jQuery);
