var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,d){a instanceof String&&(a=String(a));for(var e=a.length,f=0;f<e;f++){var l=a[f];if(c.call(d,l,f,a))return{i:f,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,d,e){if(c){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in d||(d[f]={});d=d[f]}a=a[a.length-1];e=d[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,e={next:function(){if(d<a.length){var f=d++;return{value:c(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,d){return d})}},"es8","es3");
(function(a,c){function d(g){if(g.origin===a.origin||g.origin===this.mainWindow.origin)try{var b=g.data.split(":");if("ping"==b[0])c("iframe.interactive")[0].contentWindow.postMessage("authorAPIPing:"+b[1],a.origin);else{var h=authorAPI[b[0]](b[1],b[2]);"get"==b[0]&&c("iframe.interactive")[0].contentWindow.postMessage("authorAPIGet:"+b[1]+":"+h,a.origin)}}catch(t){}}var e={bind:function(a,b){this._callbacks=this._callbacks||{};a.split(" ").forEach(function(a){this._callbacks[a]=this._callbacks[a]||
[];this._callbacks[a].push(b)},this);return this},trigger:function(){var a=Array.prototype.slice.call(arguments);var b=a.shift();(b=this._callbacks&&this._callbacks[b])&&b.forEach(function(b){b.apply(this,a)},this)},unbind:function(a,b){if(0===arguments.length)return this._callbacks={},this;if(!a)return this;for(var h in a.split(" ")){var c=this._callbacks&&this._callbacks[h];c&&(b?c.forEach(function(a,c){if(a===b){var g=g.slice();g.splice(c,1);this._callbacks[h]=g}},this):delete this._callbacks[h])}return this}},
f=function(){var a=function(b){this.url=b;this.dfd=null};a.prototype={check:function(){if(this.dfd)return this.dfd.promise();this.dfd=c.Deferred();c.get(this.url).then(function(){this.dfd.resolve(!0);this.dfd=null}.bind(this)).fail(function(b){this.dfd.resolve(!(401===b.status||403===b.status));this.dfd=null}.bind(this));return this.dfd.promise()}};return a}(),l=function(){var a=function(b,a,c){this.next=this.current=null;this.authToken=b;this.apiUrl=a;this.observer=c};a.prototype={enqueue:function(b){this.next=
this._buildAjaxFunctionFromData(b);this.current||this._processNext()},hasPending:function(){return!!this.current},_buildAjaxFunctionFromData:function(b){return c.proxy(function(){c.ajax(this.apiUrl,{type:"PUT",data:{authenticity_token:this.authToken,data:JSON.stringify(b),_method:"PUT"}}).done(c.proxy(this._processNext,this)).done(c.proxy(this._notifyObserver,this)).fail(c.proxy(this._onFail,this))},this)},_retry:function(){this.next?this._processNext():this.current()},_processNext:function(){this.current=
this.next;this.next=null;this.current&&this.current()},_notifyObserver:function(b){this.observer.update({type:"response",data:b})},_onFail:function(b){this.observer.update({type:"error",response:b.responseText});setTimeout(c.proxy(this._retry,this),2E3)}};return a}(),n=function(){var g=function(b){this.authToken=b.authToken;this.apiUrl=b.apiUrl;this.observer=new m(this,b.mainWindow);this.queues={}};g.prototype={process:function(b,a){(this.queues[b]||(this.queues[b]=new l(this.authToken,this.apiUrl,
this.observer))).enqueue(a);this.busy()},hasPending:function(){for(var b in this.queues)if(this.queues.hasOwnProperty(b)&&this.queues[b].hasPending())return!0;return!1},update:function(){this.hasPending()||this.idle()},busy:function(){c(a).off("beforeunload").on("beforeunload",function(){return"There are pending requests. If you close the window, you may lose data."})},idle:function(){c(a).off("beforeunload")}};return g}(),m=function(){var a=function(b,a){this.main=a;this.observer=b};a.prototype=
{update:function(b){this.main&&this.main.postMessage(b,"*");this.observer&&this.observer.update(b)}};return a}(),p=function(){var a=function(a){this.api=a;this.currentViewMode=null;a.ready().then(function(a){a.getBook().addEventListener("open_page",this.trigger.bind(this,"open_page"))}.bind(this))};_(a.prototype).extend(e,{setCurrentViewMode:function(a){this.currentViewMode=a},getCurrentViewMode:function(){return this.currentViewMode}});return a}(),k=function(a){var b=this;a.ready().then(function(a){return a.getBook().addEventListener("open_external_hotspot",
function(a){return b.open(a)})})};k.prototype.open=function(c){c=this.url(c);this.isMobile()?a.open(c):this.openInIframe(c)};k.prototype.close=function(){this.backdrop&&this.backdrop.remove();this.iframe&&this.iframe.remove();this.backdrop=this.iframe=null};k.prototype.isMobile=function(){return 988>=c(a).width()};k.prototype.openInIframe=function(a){var b=this,h=c("iframe#interaction").contents().find("body");this.backdrop=this.$backdrop().appendTo(h).click(function(){return b.close()});var d=this.iframe=
this.$iframe(a);d.css("visibility","hidden").appendTo(h).on("load",function(){return d.css("visibility","visible")})};k.prototype.url=function(a){return"/interactives/"+a};k.prototype.$iframe=function(a){return c("<iframe></iframe>").attr("src",a).css(this.iframeStyle()).attr({frameborder:0,scrolling:"no",allowfullscreen:!0})};k.prototype.iframeStyle=function(){return{top:"50%",left:"50%",zIndex:1050,width:"988px",height:"679px",position:"fixed",marginLeft:"-494px",marginTop:"-339.5px"}};k.prototype.$backdrop=
function(){return c("<div></div>").css(this.backdropStyle())};k.prototype.backdropStyle=function(){return{top:0,left:0,right:0,bottom:0,zIndex:1040,opacity:.7,position:"fixed",backgroundColor:"#000"}};var q=function(){var a=function(a){this.api=a};_(a.prototype).extend({set:function(a){this.data=a;this.api.initialized().then(function(a){a=a.getBook();a.register&&a.register("has-resources",this.hasResources.bind(this))}.bind(this))},hasResources:function(a){for(var b in this.data){var c=this.data[b];
if(a.page>=c.start&&a.page<=c.end)return!0}return!1}});return a}(),r=function(){var d=function(a){this.values={};this.tainted=!1;this.dfdEngineInitialized=c.Deferred();this.dfdEngineReady=c.Deferred();this.mainWindow=a;this.ajaxManager=new n({mainWindow:a});this.sessionStatus=new f("/api/profile.json");this.resourcePanelManager=new p(this);this.taggingManager=new q(this);this.hotspotManager=new k(this)};d.prototype={initializeValues:function(a){this.values=a},setEngine:function(a){var b=this;this.engine=
a;a.addEventListener("lo:submit",function(){return b.onLOSubmit()});a.addEventListener("interaction:start",function(){return b.onInteractionStart()},this,{once:!0});this.dfdEngineInitialized.resolve(a);a.ready().then(function(){this.dfdEngineReady.resolve(a)}.bind(this))},initialized:function(){return this.dfdEngineInitialized.promise()},ready:function(){return this.dfdEngineReady.promise()},setScreenIdGetterForDigitalBooks:function(){try{var a=JSON.parse(this.values.data).interaction&&"interaction"||
"interaction_0";this.getScreenIdFor=function(){return a}}catch(h){}},setTagging:function(a){this.taggingManager.set(a)},isResourcesPanelEnabled:function(){return!!this.values.show_resources_panel},resourcePanelMode:function(a){this.ready().then(function(b){b.getBook().resourcePanelMode(a)})},resourcesUrl:function(b){b=b||{};this.sessionStatus.check().then(function(b){b||(a.top.location.href="/users/login?user_return_to="+a.top.location.href)});return this._resourcesUrl||(this._resourcesUrl=function(){var c=
b.page-b.offset+1,d,e,f,g=this.resourcePanelManager.getCurrentViewMode();(d=/courses\/(\d+)/.exec(a.location.href))&&(e=d[1]);(d=/(\d+).html/.exec(a.location.href))&&(f=d[1]);c="/app/courses/"+e+"/digital_books/"+f+"/page/"+c;g&&(c=c+"/mode/"+g);return c}.call(this))},set:function(a,c){"object"==typeof console&&"function"==typeof console.log&&console.log("set key:"+a+" value:"+c);if(this.values[a]!=c){var b={};this.values[a]=b[a]=c;"undefined"!=typeof this.values.api_url&&(this.ajaxManager.authToken=
this.values.authenticity_token,this.ajaxManager.apiUrl=this.values.api_url,this.ajaxManager.process(a,b))}},get:function(a){"object"==typeof console&&"function"==typeof console.log&&console.log("get key:"+a+" value:"+this.values[a]);return this.values[a]},closeModal:function(a){var b=a.find(".interactive-dialog");b.length||(b=a.find("iframe.hotspot.modal-content").parent());b.fadeOut(function(){c(this).remove()})},closeHotspot:function(){this.hotspotManager.close()},finish:function(b){b=c(a.parent.document);
if(this.ajaxManager.hasPending())return setTimeout(this.finish.bind(this),500),!1;if(top==a)a.close();else if(_.isUndefined(top.Osp))this.closeModal(b),b.find(".modal-backdrop").remove();else try{top.Osp.InteractivePlayer.player.hideModal(),top.Osp.InteractivePlayer.player.removeModal()}catch(h){top.Backbone.Radio.channel("learning_object").request("finish")}this.mainWindow&&this.mainWindow.postMessage({type:"lo:finish"},a.origin)},notifyAnswers:function(){var b=this;try{this.engine.getLO().getUserAnswers().then(function(c){return b.mainWindow.postMessage({type:"lo:answers",
data:c},a.origin)})}catch(h){}},onLOSubmit:function(){if(this.mainWindow){var b=this.values.score,c=this.values.api_url;this.notifyAnswers();this.mainWindow.postMessage({type:"lo:submit",data:{score:b,useAPI:!!c}},a.origin)}},onInteractionStart:function(){this.mainWindow&&this.mainWindow.postMessage({type:"interaction:start"},a.origin)}};return d}();a.authorAPI=new r(top);"undefined"!=typeof a.attachEvent&&a.attachEvent("onmessage",d);"undefined"!=typeof a.addEventListener&&a.addEventListener("message",
d,!1)})(window,jQuery);
